import {
	KNOWLEDGE_SHORTCUT_DEFAULT_CHORDS,
	KNOWLEDGE_SHORTCUT_KEY_IDS,
} from '@/utils/knowledge-shortcuts';

export type ShortcutSettingItem = {
	/** i18n key；用于在 System 设置页展示 label */
	labelKey: string;
	label: string;
	key: number;
	id: string;
	shortcut: string;
	defaultShortcut: string;
	placeholder: string;
	action: string;
	/**
	 * true（默认）：绑定后调用 Tauri 注册全局快捷键；
	 * false：仅写入 store，由具体页面（如知识库）在窗口内监听。
	 */
	registerGlobally?: boolean;
	/** 写入 store 后同步到窗口菜单右侧加速键 */
	syncWindowMenu?: boolean;
};

/** 与 Rust `menu.rs` 中 WIN_SHORTCUT_* / FILE_SHORTCUT_* 对齐 */
export const WINDOW_SHORTCUT_KEYS = {
	minimize: 25,
	close: 26,
	scale: 27,
	fill: 28,
	center: 29,
	fullscreen: 30,
} as const;

export const FILE_SHORTCUT_KEYS = {
	about: 31,
	logout: 32,
	quit: 33,
} as const;

export const DEFAULT_INFO: ShortcutSettingItem[] = [
	{
		labelKey: 'setting.system.shortcuts.item.window.close',
		label: '关闭窗口',
		key: WINDOW_SHORTCUT_KEYS.close,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: 'Meta + W',
		placeholder: '按键盘输入快捷键',
		action: 'window_close',
		registerGlobally: false,
		syncWindowMenu: true,
	},
	{
		labelKey: 'setting.system.shortcuts.item.hideOrShowApp',
		label: '显示隐藏应用',
		key: 2,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: 'Meta + E',
		placeholder: '按键盘输入快捷键',
		action: 'hideOrShowApp',
		registerGlobally: true,
	},
	{
		labelKey: 'setting.system.shortcuts.item.reload',
		label: '刷新应用',
		key: 3,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: 'Command + Shift + W',
		placeholder: '按键盘输入快捷键',
		action: 'reload',
		registerGlobally: true,
	},
	{
		labelKey: 'setting.system.shortcuts.item.window.scale',
		label: '缩放窗口',
		key: WINDOW_SHORTCUT_KEYS.scale,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: 'Meta + Shift + S',
		placeholder: '按键盘输入快捷键',
		action: 'window_scale',
		registerGlobally: false,
		syncWindowMenu: true,
	},
	{
		labelKey: 'setting.system.shortcuts.item.window.minimize',
		label: '隐藏窗口',
		key: WINDOW_SHORTCUT_KEYS.minimize,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: 'Meta + M',
		placeholder: '按键盘输入快捷键',
		action: 'window_minimize',
		registerGlobally: false,
		syncWindowMenu: true,
	},
	{
		labelKey: 'setting.system.shortcuts.item.window.fill',
		label: '填充窗口',
		key: WINDOW_SHORTCUT_KEYS.fill,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: 'Meta + Shift + F',
		placeholder: '按键盘输入快捷键',
		action: 'window_fill',
		registerGlobally: false,
		syncWindowMenu: true,
	},
	{
		labelKey: 'setting.system.shortcuts.item.window.center',
		label: '居中窗口',
		key: WINDOW_SHORTCUT_KEYS.center,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: 'Meta + Shift + C',
		placeholder: '按键盘输入快捷键',
		action: 'window_center',
		registerGlobally: false,
		syncWindowMenu: true,
	},
	{
		labelKey: 'setting.system.shortcuts.item.window.fullscreen',
		label: '全屏窗口',
		key: WINDOW_SHORTCUT_KEYS.fullscreen,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: 'Control + Meta + F',
		placeholder: '按键盘输入快捷键',
		action: 'window_fullscreen',
		registerGlobally: false,
		syncWindowMenu: true,
	},
	{
		labelKey: 'setting.system.shortcuts.item.file.about',
		label: '关于应用',
		key: FILE_SHORTCUT_KEYS.about,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: 'Meta + Shift + A',
		placeholder: '按键盘输入快捷键',
		action: 'file_about',
		registerGlobally: false,
		syncWindowMenu: true,
	},
	{
		labelKey: 'setting.system.shortcuts.item.file.logout',
		label: '退出登录',
		key: FILE_SHORTCUT_KEYS.logout,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: 'Meta + Shift + L',
		placeholder: '按键盘输入快捷键',
		action: 'file_logout',
		registerGlobally: false,
		syncWindowMenu: true,
	},
	{
		labelKey: 'setting.system.shortcuts.item.file.quit',
		label: '退出应用',
		key: FILE_SHORTCUT_KEYS.quit,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: 'Meta + Q',
		placeholder: '按键盘输入快捷键',
		action: 'file_quit',
		registerGlobally: false,
		syncWindowMenu: true,
	},
	{
		labelKey: 'setting.system.shortcuts.item.knowledge.save',
		label: '知识库：保存',
		key: KNOWLEDGE_SHORTCUT_KEY_IDS.save,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: KNOWLEDGE_SHORTCUT_DEFAULT_CHORDS.save,
		placeholder: '按键盘输入快捷键',
		action: 'knowledge_save',
		registerGlobally: false,
	},
	{
		labelKey: 'setting.system.shortcuts.item.knowledge.import',
		label: '知识库：导入文件',
		key: KNOWLEDGE_SHORTCUT_KEY_IDS.import,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: KNOWLEDGE_SHORTCUT_DEFAULT_CHORDS.import,
		placeholder: '按键盘输入快捷键',
		action: 'knowledge_import',
		registerGlobally: false,
	},
	{
		labelKey: 'setting.system.shortcuts.item.knowledge.clearDraft',
		label: '知识库：清空草稿',
		key: KNOWLEDGE_SHORTCUT_KEY_IDS.clear,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: KNOWLEDGE_SHORTCUT_DEFAULT_CHORDS.clear,
		placeholder: '按键盘输入快捷键',
		action: 'knowledge_clear',
		registerGlobally: false,
	},
	{
		labelKey: 'setting.system.shortcuts.item.knowledge.share',
		label: '知识库：分享文章',
		key: KNOWLEDGE_SHORTCUT_KEY_IDS.share,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: KNOWLEDGE_SHORTCUT_DEFAULT_CHORDS.share,
		placeholder: '按键盘输入快捷键',
		action: 'knowledge_share',
		registerGlobally: false,
	},
	{
		labelKey: 'setting.system.shortcuts.item.knowledge.openList',
		label: '知识库：打开列表',
		key: KNOWLEDGE_SHORTCUT_KEY_IDS.openLibrary,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: KNOWLEDGE_SHORTCUT_DEFAULT_CHORDS.openLibrary,
		placeholder: '按键盘输入快捷键',
		action: 'knowledge_open_library',
		registerGlobally: false,
	},
	{
		labelKey: 'setting.system.shortcuts.item.knowledge.toggleActionBar',
		label: '知识库：切换操作栏',
		key: KNOWLEDGE_SHORTCUT_KEY_IDS.toggleMarkdownBottomBar,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: KNOWLEDGE_SHORTCUT_DEFAULT_CHORDS.toggleMarkdownBottomBar,
		placeholder: '按键盘输入快捷键',
		action: 'knowledge_toggle_markdown_bottom_bar',
		registerGlobally: false,
	},
	{
		labelKey: 'setting.system.shortcuts.item.knowledge.openTrash',
		label: '知识库：打开回收站',
		key: KNOWLEDGE_SHORTCUT_KEY_IDS.openTrash,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: KNOWLEDGE_SHORTCUT_DEFAULT_CHORDS.openTrash,
		placeholder: '按键盘输入快捷键',
		action: 'knowledge_open_trash',
		registerGlobally: false,
	},
	{
		labelKey:
			'setting.system.shortcuts.item.knowledge.sendSelectionToAssistant',
		label: '知识库：发送选中内容到助手输入框',
		key: KNOWLEDGE_SHORTCUT_KEY_IDS.pasteToAssistant,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: KNOWLEDGE_SHORTCUT_DEFAULT_CHORDS.pasteToAssistant,
		placeholder: '按键盘输入快捷键',
		action: 'knowledge_send_selection_to_assistant',
		registerGlobally: false,
	},
	{
		labelKey: 'setting.system.shortcuts.item.knowledge.bar.editSource',
		label: '知识库：操作栏：编辑源码',
		key: KNOWLEDGE_SHORTCUT_KEY_IDS.markdownBarAction1,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: KNOWLEDGE_SHORTCUT_DEFAULT_CHORDS.markdownBarAction1,
		placeholder: '按键盘输入快捷键',
		action: 'knowledge_markdown_bar_action_1',
		registerGlobally: false,
	},
	{
		labelKey: 'setting.system.shortcuts.item.knowledge.bar.diff',
		label: '知识库：操作栏：分屏对照（Diff）',
		key: KNOWLEDGE_SHORTCUT_KEY_IDS.markdownBarAction2,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: KNOWLEDGE_SHORTCUT_DEFAULT_CHORDS.markdownBarAction2,
		placeholder: '按键盘输入快捷键',
		action: 'knowledge_markdown_bar_action_2',
		registerGlobally: false,
	},
	{
		labelKey: 'setting.system.shortcuts.item.knowledge.bar.previewRender',
		label: '知识库：操作栏：预览渲染',
		key: KNOWLEDGE_SHORTCUT_KEY_IDS.markdownBarAction3,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: KNOWLEDGE_SHORTCUT_DEFAULT_CHORDS.markdownBarAction3,
		placeholder: '按键盘输入快捷键',
		action: 'knowledge_markdown_bar_action_3',
		registerGlobally: false,
	},
	{
		labelKey: 'setting.system.shortcuts.item.knowledge.bar.toggleAssistant',
		label: '知识库：操作栏：开关 AI 助手',
		key: KNOWLEDGE_SHORTCUT_KEY_IDS.markdownBarAction4,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: KNOWLEDGE_SHORTCUT_DEFAULT_CHORDS.markdownBarAction4,
		placeholder: '按键盘输入快捷键',
		action: 'knowledge_markdown_bar_action_4',
		registerGlobally: false,
	},
	{
		labelKey: 'setting.system.shortcuts.item.knowledge.bar.splitPreview',
		label: '知识库：操作栏：分屏预览',
		key: KNOWLEDGE_SHORTCUT_KEY_IDS.markdownBarAction5,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: KNOWLEDGE_SHORTCUT_DEFAULT_CHORDS.markdownBarAction5,
		placeholder: '按键盘输入快捷键',
		action: 'knowledge_markdown_bar_action_5',
		registerGlobally: false,
	},
	{
		labelKey: 'setting.system.shortcuts.item.knowledge.bar.followBidirectional',
		label: '知识库：操作栏：双边跟随',
		key: KNOWLEDGE_SHORTCUT_KEY_IDS.markdownBarAction6,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: KNOWLEDGE_SHORTCUT_DEFAULT_CHORDS.markdownBarAction6,
		placeholder: '按键盘输入快捷键',
		action: 'knowledge_markdown_bar_action_6',
		registerGlobally: false,
	},
	{
		labelKey:
			'setting.system.shortcuts.item.knowledge.bar.followPreviewFollowsEditor',
		label: '知识库：操作栏：右边跟随左边',
		key: KNOWLEDGE_SHORTCUT_KEY_IDS.markdownBarAction7,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: KNOWLEDGE_SHORTCUT_DEFAULT_CHORDS.markdownBarAction7,
		placeholder: '按键盘输入快捷键',
		action: 'knowledge_markdown_bar_action_7',
		registerGlobally: false,
	},
	{
		labelKey:
			'setting.system.shortcuts.item.knowledge.bar.followEditorFollowsPreview',
		label: '知识库：操作栏：左边跟随右边',
		key: KNOWLEDGE_SHORTCUT_KEY_IDS.markdownBarAction8,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: KNOWLEDGE_SHORTCUT_DEFAULT_CHORDS.markdownBarAction8,
		placeholder: '按键盘输入快捷键',
		action: 'knowledge_markdown_bar_action_8',
		registerGlobally: false,
	},
	{
		labelKey: 'setting.system.shortcuts.item.knowledge.bar.toggleOverrideSave',
		label: '知识库：操作栏：开关覆盖保存',
		key: KNOWLEDGE_SHORTCUT_KEY_IDS.markdownBarAction9,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: KNOWLEDGE_SHORTCUT_DEFAULT_CHORDS.markdownBarAction9,
		placeholder: '按键盘输入快捷键',
		action: 'knowledge_markdown_bar_action_9',
		registerGlobally: false,
	},
	{
		labelKey: 'setting.system.shortcuts.item.knowledge.bar.toggleAutoSave',
		label: '知识库：操作栏：开关自动保存',
		key: KNOWLEDGE_SHORTCUT_KEY_IDS.markdownBarAction0,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: KNOWLEDGE_SHORTCUT_DEFAULT_CHORDS.markdownBarAction0,
		placeholder: '按键盘输入快捷键',
		action: 'knowledge_markdown_bar_action_0',
		registerGlobally: false,
	},
	{
		labelKey: 'setting.system.shortcuts.item.knowledge.bar.resetPosition',
		label: '知识库：操作栏：复位初始位置',
		key: KNOWLEDGE_SHORTCUT_KEY_IDS.markdownBarResetPosition,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: KNOWLEDGE_SHORTCUT_DEFAULT_CHORDS.markdownBarResetPosition,
		placeholder: '按键盘输入快捷键',
		action: 'knowledge_markdown_bar_reset_position',
		registerGlobally: false,
	},
	{
		labelKey: 'setting.system.shortcuts.item.newWorkflow',
		label: '新建工作流',
		key: 4,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: 'Command + N',
		placeholder: '按键盘输入快捷键',
		action: 'new_workflow',
		registerGlobally: true,
	},
	{
		labelKey: 'setting.system.shortcuts.item.openSubwindow',
		label: '打开子窗口',
		key: 5,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: 'Ctrl + Shift + L',
		placeholder: '按键盘输入快捷键',
		action: 'open_subwindow',
		registerGlobally: true,
	},
];
