export default {
	extends: ['@commitlint/config-conventional'],
	rules: {
		'type-enum': [
			2,
			'always',
			[
				'feat',
				'bug',
				'fix',
				'ui',
				'docs',
				'style',
				'perf',
				'release',
				'deploy',
				'refactor',
				'test',
				'chore',
				'revert',
				'merge',
				'other',
				'build',
			],
		],
		'type-case': [2, 'always', 'lower-case'],
		'type-empty': [2, 'never'],
		'subject-case': [2, 'always', 'lower-case'],
		'subject-empty': [2, 'never'],
		'header-max-length': [0, 'always', 72],
	},
};
