#!/usr/bin/env python3
"""
全面修复 docs/ 下所有文档中残留的英文文件名链接。
扫描所有 .md 文件，找出指向旧英文名的链接并替换为新的中文名。
"""

import os
import re

BASE = "/Users/dnhyxc/Documents/code/dnhyxc-ai/docs"

# 旧英文名 -> 新中文名 的完整映射（key 是不含路径和扩展名的基础名）
RENAME_MAP = {
    # === english/ ===
    "rich-editor-core-fixes": "富文本编辑器核心修复",
    "rich-editor-doc-edge-nav": "富文本编辑器边缘导航",
    "richeditor-performance-tuning": "富文本编辑器性能调优",
    "selection-speak-context-menu": "选中文本朗读菜单",
    "sidebar-ui-unify": "侧边栏UI统一",
    "tauri-clipboard-image-files": "Tauri剪贴板图片文件",
    "tauri-clipboard-tiptap": "Tauri剪贴板富文本",
    "tts-awaiting-callback-refine": "TTS回调优化",
    "tts-edge-unify-stream": "EdgeTTS统一流式",
    "tts-end-to-end-guide": "TTS端到端指南",
    "tts-local-cancel-settle": "TTS本地取消结算影响",
    "tts-membership-routing": "TTS会员路由",
    "tts-playback-source": "TTS播放源",
    "tts-tauri-cloud-playback": "TTS桌面端云端播放影响",
    "vocab-favorite-status-query": "单词收藏状态查询",
    "vocab-segmentation-import": "单词分词导入",
    "vocabulary-mistakes-and-shared-ui": "单词错题与共享UI",
    "voice-settings-page": "语音设置页",
    "xfyun-cloud-tts": "讯飞云TTS",
    "classic-practice-and-mistakes": "经典练习与错题",
    "classic-quotes-library-import": "经典语句库导入",
    "cloud-tts-cadence-prefetch": "云端TTS节奏预取",
    "cloud-tts-edge-voice": "云端TTS边缘语音",
    "cloud-tts-prefs-db": "云端TTS偏好数据库",
    "cloud-tts-segment-pipeline": "云端TTS分段管线",
    "cloud-tts-settings": "云端TTS设置",
    "cloud-tts-user-credentials": "云端TTS用户凭据",
    "daily-memorize-implementation": "每日记词实现",
    "daily-quiz-distractors-ui": "每日测验干扰项UI",
    "english-agent-multi-session-history-sse": "英语Agent多会话历史SSE",
    "english-agent-organics-ui": "英语Agent组织结构UI",
    "english-agent-stream-perf-isolation": "英语Agent流式性能隔离",
    "english-favorites-docx-export": "英语收藏DOCX导出",
    "english-learning-backend-implementation": "英语学习后端实现",
    "english-learning-count-optional": "英语学习计数可选",
    "english-learning-favorites-by-id": "英语收藏按ID查询",
    "english-learning-favorites-drawer": "英语收藏抽屉",
    "english-learning-favorites-toolbar-sql": "英语收藏工具栏SQL",
    "english-learning-gen-robustness": "英语学习生成鲁棒性",
    "english-learning-impl-overview": "英语学习实现概述",
    "english-learning-json-import": "英语学习JSON导入",
    "english-learning-library-import": "英语学习文库导入",
    "english-learning-library-ux-and-delete": "英语学习文库UX与删除",
    "english-learning-list-collapse-toggle": "英语学习列表折叠切换",
    "english-learning-list-network-retry": "英语学习列表网络重试",
    "english-learning-master-agent-web-search-to-llm": "英语学习主Agent联网搜索转LLM",
    "english-learning-master-research-web-autonomous": "英语学习主研究Web自主",
    "english-learning-no-level": "英语学习无等级",
    "english-learning-pack-agent-stall-ipa": "英语词包Agent停顿IPA",
    "english-learning-pack-favorites": "英语词包收藏",
    "english-learning-pack-history-ux": "英语词包历史UX",
    "english-learning-pack-session-items": "英语词包会话项",
    "english-learning-pack-session-storage": "英语词包会话存储",
    "english-learning-pack-sse": "英语词包SSE",
    "english-learning-pack-stream-route": "英语词包流式路由",
    "english-learning-quick-intents-input": "英语学习快捷意图输入",
    "english-learning-sidebar-persist": "英语学习侧边栏持久化",
    "english-learning-stream-cancel-http-silent": "英语学习流式取消HTTP静默",
    "english-learning-submodel-prompt-thread": "英语学习子模型提示线程",
    "english-learning-topic-match-db-sse": "英语学习主题匹配数据库SSE",
    "english-learning-vocab-classic-impl-detail": "英语学习单词经典实现细节",
    "english-learning-vocab-ui-refactor": "英语学习单词UI重构",
    "english-module-folder-layout": "英语模块文件夹布局",
    "english-pack-stream-store": "英语词包流式存储",
    "english-pack-websearch-hist": "英语词包联网搜索历史",
    "english-tts-cache-consistency": "英语TTS缓存一致性",
    "english-tts-local-voice": "英语TTS本地语音",
    "english-tts-playback": "英语TTS播放",
    "english-tts-stop-cleanup": "英语TTS停止清理",
    "english-vocab-history": "英语单词历史",
    "english-vocabulary-pos": "英语单词词性",
    "favorite-star-incremental-ui": "收藏星增量UI",
    "learning-notes-crud": "学习笔记CRUD",
    "learning-notes-dirty-save": "学习笔记脏保存",
    "learning-notes-docx-builder": "学习笔记DOCX构建",
    "learning-notes-editor-polish": "学习笔记编辑器打磨",
    "learning-notes-export-perf": "学习笔记导出性能",
    "learning-notes-image-inline-style": "学习笔记图片内联样式",
    "learning-notes-large-note-editor": "学习笔记大编辑器",
    "learning-notes-mobx-store": "学习笔记MobX存储",
    "learning-notes-public-list": "学习笔记公开列表",
    "learning-notes-remote": "学习笔记远程",
    "learning-notes-rich-editor-deep-dive": "学习笔记富文本编辑器深潜",
    "learning-notes-save-focus-title": "学习笔记保存聚焦标题",
    "learning-notes-windowed-preview": "学习笔记窗口化预览",
    "library-public-edit": "文库公开编辑",
    "library-words-list-cache": "文库单词列表缓存",
    "minimax-chinese-voices": "MiniMax中文语音",
    "minimax-cloud-tts": "MiniMax云端TTS",
    "practice-entry-navigation": "练习入口导航",
    "practice-keyboard-previous": "练习键盘上一个",
    "practice-reveal-playback-continuity": "练习揭示播放连续性",
    "practice-review-srs": "练习复习SRS",
    "practice-session-controls": "练习会话控件",
    "practice-session-hint": "练习会话提示",
    "practice-summary-ui": "练习总结UI",
    "practice-wrong-panel-shortcuts": "练习错题面板快捷键",
    "cloud-tts-minimax-model-settings": "云端TTS MiniMax模型设置影响",
    "cloud-tts-edge-prosody-membership": "云端TTS边缘韵律会员影响",
    "cloud-tts-user-credentials-fallback": "云端TTS用户凭据回退影响",

    # === ebook/ ===
    "ebook-assistant-stream-patch-scheduler": "电子书助手流式补丁调度",
    "ebook-cos-local-shelf": "电子书COS本地书架",
    "ebook-cos-object-key-resolve": "电子书COS对象键解析",
    "ebook-cos-stream-io": "电子书COS流式IO",
    "ebook-folder-archive": "电子书文件夹归档",
    "ebook-list-scroll-cycle": "电子书列表滚动循环",
    "ebook-local-path-dedup": "电子书本地路径去重",
    "ebook-membership-upload": "电子书会员上传",
    "ebook-moke-assistant": "电子书Mock助手",
    "ebook-plugin-ideas-list": "电子书插件想法列表",
    "ebook-reader-shelf": "电子书阅读书架",
    "ebook-shelf-card-uncategorized": "电子书书架卡片未分类",
    "ebook-shelf-category": "电子书书架分类",
    "ebook-shelf-progress-pct": "电子书书架进度百分比",
    "ebook-shelf-sort-last-read": "电子书书架排序最近阅读",
    "ebook-toc-active-highlight": "电子书目录激活高亮",
    "epub-annotation-sync-perf": "EPUB注释同步性能",
    "epub-assistant-context-menu": "EPUB助手右键菜单",
    "epub-chapter-listen": "EPUB章节听书",
    "epub-chrome-list-active-theme": "EPUB Chrome列表激活主题",
    "epub-context-menu-popbar": "EPUB右键菜单PopBar",
    "epub-highlight-custom-color": "EPUB划线自定义颜色",
    "epub-highlight-dom-match": "EPUB划线DOM匹配",
    "epub-listen-audio-end-ui": "EPUB听书音频结束UI",
    "epub-listen-auto-follow-fab": "EPUB听书自动跟随浮动按钮",
    "epub-listen-bar-chapter-nav": "EPUB听书栏章节导航",
    "epub-listen-bar-loading-controls": "EPUB听书栏加载控件",
    "epub-listen-bar-playhead-toc": "EPUB听书栏播放头目录",
    "epub-listen-bg-resize-relayout": "EPUB听书背景重布局",
    "epub-listen-follow-cfi-remount": "EPUB听书跟随CFI重挂载",
    "epub-listen-host-overlay": "EPUB听书宿主覆盖层",
    "epub-listen-loading-while-await": "EPUB听书等待加载",
    "epub-listen-play-loading": "EPUB听书播放加载",
    "epub-listen-playback-fixes-2026-07": "EPUB听书播放修复2026-07",
    "epub-listen-player-bar-ruler-ui": "EPUB听书播放器栏标尺UI",
    "epub-listen-player-bar": "EPUB听书播放器栏",
    "epub-listen-popbar-dismiss": "EPUB听书PopBar关闭",
    "epub-listen-prefetch-after-start": "EPUB听书启动后预取",
    "epub-listen-quote-continue": "EPUB听书引用继续",
    "epub-listen-rate-after-src": "EPUB听书源后速率",
    "epub-listen-rate-persist": "EPUB听书速率持久化",
    "epub-listen-select-pause-follow": "EPUB听书选择暂停跟随",
    "epub-listen-sentence-bg": "EPUB听书句背景",
    "epub-listen-soft-pause": "EPUB听书软暂停",
    "epub-listen-toc-anchor-start": "EPUB听书目录锚点启动",
    "epub-listen-toc-chapter-restart": "EPUB听书目录章节重启",
    "epub-listen-touchbar-loading": "EPUB听书触控栏加载",
    "epub-listen-user-highlight-reconcile": "EPUB听书用户划线对账",
    "epub-popbar-perf-ux": "EPUB PopBar性能体验",
    "epub-public-thought-underline-overlay": "EPUB公开想法下划线覆盖",
    "epub-quote-listen": "EPUB引用听书",
    "epub-quote-share-dialog-chrome": "EPUB引用分享对话框Chrome",
    "epub-quote-share": "EPUB引用分享",
    "epub-read-page-nav-dismiss": "EPUB阅读页导航关闭",
    "epub-read-split-panel": "EPUB阅读分屏",
    "epub-reader-chrome-contrast": "EPUB阅读器Chrome对比度",
    "epub-reader-settings-dismiss": "EPUB阅读器设置关闭",
    "epub-reader-settings-scroll": "EPUB阅读器设置滚动",
    "epub-reader-surface-bg": "EPUB阅读器表面背景",
    "epub-reading-thoughts": "EPUB阅读想法",
    "epub-scrolled-toc-nav-align": "EPUB滚动目录导航对齐",
    "epub-selection-popbar-chrome": "EPUB选区PopBar Chrome",
    "epub-selection-popbar-visual": "EPUB选区PopBar视觉",
    "epub-selection-scroll-clear": "EPUB选区滚动清除",
    "epub-selection-scroll-target-filter": "EPUB选区滚动目标过滤",
    "epub-settings-range-repaint": "EPUB设置范围重绘",
    "epub-side-panel-input-focus": "EPUB侧面板输入焦点",
    "epub-split-soft-resize": "EPUB分屏软调整",
    "epub-thought-cluster-bridging": "EPUB想法聚类桥接",
    "epub-thought-drawer": "EPUB想法抽屉",
    "epub-thought-list-delete-close": "EPUB想法列表删除关闭",
    "epub-thought-list-ui": "EPUB想法列表UI",
    "epub-thought-partial-overlap": "EPUB想法部分重叠",
    "epub-thought-quote-highlight-toggle": "EPUB想法引用划线切换",
    "epub-thought-quote-viewport": "EPUB想法引用视口",
    "epub-thought-side-panel": "EPUB想法侧面板",
    "epub-thought-underline-empty-gap": "EPUB想法下划线空白间隙",
    "epub-thought-underline-impl": "EPUB想法下划线实现",
    "epub-thought-underlines-sync": "EPUB想法下划线同步",
    "epub-thought-user-highlight-overlap": "EPUB想法用户划线重叠",
    "epub-thought-viewport-perf": "EPUB想法视口性能",
    "epub-toc-active-cfi": "EPUB目录激活CFI",
    "epub-toc-cfi-navigate": "EPUB目录CFI导航",
    "epub-tts-separator-filter": "EPUB TTS分隔符过滤",
    "epub-user-highlight-impl": "EPUB用户划线实现",
    "epub-viewport-pin": "EPUB视口定位",
    "listen-exclusive-control": "听书互斥控制",
    "miniprogram-epub-server-parse": "小程序EPUB服务端解析",
    "pdf-reader-fit-scroll": "PDF阅读器适配滚动",
    "shelf-cover-title": "书架封面标题",
    "shelf-reader-polish": "书架阅读打磨",
    "tts-audio-progress-sync": "TTS音频进度同步",
    "epub-all-features-dev": "EPUB全特性开发",
    "epub-listen-dev": "EPUB听书开发",
    "epub-mark-layers-shared": "EPUB标注分层共享",
    "epub-thought-add-underline-dev": "EPUB想法添加下划线开发",
    "epub-user-highlight-dev": "EPUB用户划线开发",

    # === app/ ===
    "block-file-drop-nav": "文件拖放导航屏蔽",
    "build-optimization": "构建优化",
    "http-network-error-toast": "HTTP网络错误提示",
    "learning-notes-implementation": "学习笔记实现",
    "pick-file-object": "选择文件对象",
    "unified-file-selection": "统一文件选择",
    "voice-input-implementation": "语音输入实现",

    # === auth/ ===
    "home-steps-register-login-query": "首页注册登录查询",
    "login-cloud-tts-prefetch-401": "登录云端TTS预取401",
    "login-password-secret-input-tab": "登录密码SecretInput标签",
    "logout-unify-theme-sync": "登出统一主题同步",
    "membership-store-circular-deps": "会员存储循环依赖",
    "route-auth": "路由认证",
    "secret-input-component": "SecretInput组件",
    "setting-api-key-secret-input": "设置API密钥SecretInput",
    "user-switch-state-reset": "用户切换状态重置",
    "wechat-mini-program-login-bind": "微信小程序登录绑定",

    # === chat/ ===
    "assistant-selection-speak-guide": "助手选区朗读指南",
    "assistant-share-bar": "助手分享栏",
    "chat-memory-oom": "对话内存溢出",
    "chat-update": "对话更新",
    "chat-upload-access-prod": "对话上传生产访问",
    "chat-upload-preview": "对话上传预览",
    "chatbot": "聊天机器人",
    "message-actions-speak-content": "消息操作朗读内容",
    "selection-speak-common": "选区朗读通用",
    "selection-speak-media-session": "选区朗读媒体会话",
    "share-knowledge-timezone": "分享知识时区",
    "share": "分享",
    "streaming-code-block-scroll": "流式代码块滚动",
    "streaming-selection-preserve": "流式选区保持",
    "web-search": "联网搜索",

    # === cos/ ===
    "cos-dev-http-proxy": "COS开发HTTP代理",
    "cos-object-storage": "COS对象存储",

    # === ideas/ ===
    "dynamic-module-federation-microfrontend": "动态模块联邦微前端",
    "ebook-multi-user-thought-viewport-perf": "电子书多用户想法视口性能",
    "ebook-plugin-dynamic-integration": "电子书插件动态集成",
    "ebook-public-thought-live-sync": "电子书公开想法实时同步",
    "ebook-reading-progress-save": "电子书阅读进度保存",
    "ebook-thought-sync-perf-optimization": "电子书想法同步性能优化",
    "epub-listen-core-logic": "EPUB听书核心逻辑",
    "epub-listen-paragraph-tts": "EPUB听书段落朗读",
    "epub-listen-playback-optimize": "EPUB听书播放优化",
    "epub-mark-epubjs-primitives": "EPUB标注epubjs基础",
    "epub-mark-layers": "EPUB标注分层",
    "epub-public-thought-underline-overlay-fix": "EPUB公开想法下划线修复",
    "epub-scroll-multi-iframe-listen": "EPUB滚动多iframe听书",
    "epub-scroll-stutter-perf": "EPUB滚动卡顿性能",
    "epub-toc-chapter-top-align": "EPUB目录章节顶部对齐",
    "federation-kit-extract": "联邦工具提取",
    "knowledge-preview-assistant-perf": "知识预览助手性能",
    "knowledge-scroll-jank-fix-steps": "知识库滚动卡顿修复",
    "learning-notes-docx-export-handbook": "学习笔记DOCX导出手册",
    "learning-notes-editor-preview-jank": "学习笔记编辑器预览卡顿",
    "learning-notes-export-and-editor-polish": "学习笔记导出与编辑打磨",
    "learning-notes-list-export": "学习笔记列表导出",
    "learning-notes-rich-editor": "学习笔记富文本编辑",
    "mf-css-isolation": "模块联邦CSS隔离",
    "mf-style-isolation-implementation": "模块联邦样式隔离实现",
    "micro-frontend-architecture": "微前端架构",
    "miniprogram-epub-parse-logic": "小程序EPUB解析逻辑",
    "tauri-clipboard-rich-paste": "Tauri剪贴板富文本粘贴",
    "tauri-system-menu-shortcuts": "Tauri系统菜单快捷键",
    "tauri-window-zoom-unveil": "Tauri窗口缩放揭示",
    "third-party-mf-plugin-onboarding": "第三方联邦插件接入",
    "vue-plugin-hmr-bridge": "Vue插件HMR桥接",
    "wechat-miniprogram-epub-reader": "微信小程序EPUB阅读器",
    "xfyun-cloud-tts": "讯飞云TTS",

    # === impact/ ===
    "app-tauri-http-retry": "Tauri HTTP重试影响",
    "auth-wechat-mini-program-bind": "微信小程序绑定影响",
    "chat-stream-selection-preserve": "对话流式选区保持影响",
    "cloud-tts-edge-prosody-membership": "云端TTS边缘韵律会员影响",
    "cloud-tts-minimax-model-settings": "云端TTS MiniMax模型设置影响",
    "cloud-tts-user-credentials-fallback": "云端TTS用户凭据回退影响",
    "ebook-progress-remote-debounce": "电子书进度远程防抖影响",
    "ebook-public-share": "电子书公开分享影响",
    "ebook-shelf-empty-tab-reset": "电子书书架空标签重置影响",
    "english-agent-selection-speak": "英语Agent选区朗读影响",
    "english-agent-stream-input-perf": "英语Agent流式输入性能影响",
    "epub-ask-stream-selection-clear": "EPUB提问流式选区清除影响",
    "epub-highlight-custom-color-picker": "EPUB划线自定义颜色选择器影响",
    "epub-listen-bg-vs-annotations": "EPUB听书背景与注释影响",
    "epub-listen-cadence-lead": "EPUB听书节奏引导影响",
    "epub-listen-cloud-prefetch": "EPUB听书云端预取影响",
    "epub-listen-follow-fab-layout": "EPUB听书跟随浮动按钮布局影响",
    "epub-listen-player-bar-ui": "EPUB听书播放器栏UI影响",
    "epub-listen-resize-relayout": "EPUB听书尺寸重布局影响",
    "epub-listen-sentence-leading-punct": "EPUB听书句首标点影响",
    "epub-listen-utils-consolidation": "EPUB听书工具整合影响",
    "epub-mark-shared-extraction": "EPUB标注共享提取影响",
    "epub-miniprogram-server-parse": "EPUB小程序服务端解析影响",
    "epub-public-thought-live-sync": "EPUB公开想法实时同步影响",
    "epub-quote-listen-player-bar": "EPUB引用听书播放器栏影响",
    "epub-scroll-listen-section-advance": "EPUB滚动听书章节前进影响",
    "epub-thought-loader-full-fetch-removal": "EPUB想法加载全量获取移除影响",
    "epub-thought-viewport-mark": "EPUB想法视口标注影响",
    "epub-window-resize-relayout": "EPUB窗口尺寸重布局影响",
    "knowledge-assistant-stream-stick": "知识库助手流式吸附影响",
    "knowledge-editor-long-text-perf": "知识编辑器长文本性能影响",
    "knowledge-preview-assistant-pane-perf": "知识库预览助手面板性能影响",
    "knowledge-preview-code-toolbar-scroll": "知识预览代码工具条滚动",
    "monaco-markdown-view-panel": "Monaco Markdown视图面板影响",
    "plugin-host-error-actions": "插件宿主错误处理",
    "tts-edge-unify-stream-endpoint": "TTS边缘统一流式端点影响",
    "tts-local-cancel-settle": "TTS本地取消结算影响",
    "tts-tauri-cloud-playback": "TTS桌面端云端播放影响",
    "ui-tint-polish": "UI色调打磨",

    # === knowledge/ ===
    "assistant-insert-focus": "助手插入焦点",
    "assistant-stream-end-scroll-pin": "助手流式结束滚动定位",
    "auto-save": "自动保存",
    "knowledge-assistant-complete": "知识库助手完成",
    "knowledge-assistant-ephemeral-persistence": "知识库助手临时持久化",
    "knowledge-assistant-insert-selection-ai-rag": "知识库助手插入选区AI检索",
    "knowledge-assistant-layout-scrollbar-alignment": "知识库助手布局滚动条对齐",
    "knowledge-assistant-mermaid-streaming": "知识库助手Mermaid流式",
    "knowledge-assistant-multi-session-backend-implementation": "知识库助手多会话后端实现",
    "knowledge-assistant-multi-session-frontend-implementation": "知识库助手多会话前端实现",
    "knowledge-assistant-outline-toc-prepend": "知识库助手大纲目录前置",
    "knowledge-assistant-prompt-cards": "知识库助手提示卡片",
    "knowledge-assistant-stream-ux": "知识库助手流式体验",
    "knowledge-assistant-streaming-across-documents": "知识库助手跨文档流式",
    "knowledge-chunk-boundaries": "知识分块边界",
    "knowledge-chunk-infinite-loop-oom": "知识分块死循环内存溢出",
    "knowledge-editor-long-text-perf": "知识编辑器长文本性能",
    "knowledge-editor-send-selection-to-assistant-dedupe": "知识编辑器发送选区助手去重",
    "knowledge-md-import": "知识Markdown导入",
    "knowledge-member-vector-tier": "知识会员向量分层",
    "knowledge-preview-assistant-perf": "知识预览助手性能",
    "knowledge-preview-code-toolbar-scroll": "知识预览代码工具条滚动",
    "knowledge-preview-scroll-jank": "知识预览滚动卡顿",
    "knowledge-rag-implementation-backend": "知识RAG后端实现",
    "knowledge-rag-qa-assistant-frontend": "知识RAG问答助手前端",
    "knowledge-save-body-limit": "知识保存正文限制",
    "knowledge-save-format-before-persist": "知识保存格式化前置",
    "knowledge-vector-create-llm": "知识向量创建LLM",
    "local-folder-and-monaco-sync": "本地文件夹与Monaco同步",
    "rag-retrieval-nestjs-react-qdrant": "RAG检索NestJS React Qdrant",
    "shortcuts": "快捷键",
    "siliconflow-vector-full-url": "硅基向量完整URL",
    "unauthenticated-local-only": "未认证仅本地",
    "user-vector-rag-config": "用户向量RAG配置",
    "vector-bge-global-round": "向量BGE全局轮次",

    # === llm/ ===
    "agent-create-llm-unify": "Agent创建LLM统一",
    "create-llm": "创建LLM",
    "llm-runtime-settings": "LLM运行时设置",
    "llm-setting-save-flow": "LLM设置保存流程",
    "llm-setting-ui-presets": "LLM设置UI预设",
    "membership-per-user-llm": "会员单用户LLM",
    "ocr-create-llm-glm": "OCR创建LLM GLM",
    "siliconflow-chat-unification": "硅基对话统一",

    # === mermaid/ ===
    "fence-toolbar-sticky": "围栏工具条吸顶",
    "markdown-zoom-and-preview": "Markdown缩放与预览",

    # === meta/ ===
    "project-features-update": "项目功能更新",
    "release-wiki-sync": "发布Wiki同步",

    # === monaco/ ===
    "clipboard-global-handler-bypass": "剪贴板全局处理绕过",
    "cut-line-without-selection-cmd-x": "无选区剪切行Cmd+X",
    "editor-tauri-layout": "编辑器Tauri布局",
    "markdown-bottom-bar": "Markdown底部栏",
    "markdown-codeblock-prettier-format": "Markdown代码块Prettier格式化",
    "markdown-editor-context-menu": "Markdown编辑器右键菜单",
    "markdown-fence-tsx-highlight-and-prettier-format": "Markdown围栏TSX高亮与Prettier格式化",
    "markdown-ime-ghosting": "Markdown输入法鬼影",
    "markdown-preview-edit-scroll-restore": "Markdown预览编辑滚动恢复",
    "markdown-preview-toc-hash-navigation": "Markdown预览目录哈希导航",
    "markdown-split-diff-compare": "Markdown分屏差异对比",
    "markdown-split-scroll-sync": "Markdown分屏滚动同步",
    "markdown-view-panel-scroll": "Markdown视图面板滚动",
    "monaco-component-usage": "Monaco组件用法",
    "parser-markdown-preview-pane": "解析器Markdown预览窗格",

    # === ops/ ===
    "deploy": "部署",
    "nginx": "Nginx配置",
    "remote-static-resources": "远程静态资源",
    "remotes-no-store-cache": "远程无存储缓存",
    "remotes-registry-static": "远程注册静态",
    "server-deployment": "服务器部署",
    "trust-proxy-rate-limit": "代理信任与限流",
    "upload-storage-paths": "上传存储路径",

    # === pay/ ===
    "membership-active-hook": "会员激活钩子",
    "membership-grant-idempotency": "会员开通幂等",
    "stripe-membership-billing": "Stripe会员计费",

    # === plugins/ ===
    "dynamic-plugin-system": "动态插件系统",
    "ebook-host-surface-plugins": "电子书宿主表面插件",
    "federation-kit-migration": "联邦工具迁移",
    "host-plugin-integration-guide": "宿主插件集成指南",
    "mf-implementation-guide": "模块联邦实现指南",
    "mf-manifest-dedup": "模块联邦清单去重",
    "mf-plugin-host": "模块联邦插件宿主",
    "mf-plugin-locale-sync": "模块联邦插件语言同步",
    "mf-shared-react-router": "模块联邦共享React路由",
    "plugin-card-border-theme": "插件卡片边框主题",
    "plugin-cinema-fullscreen": "插件影院全屏",
    "plugin-development-guide": "插件开发指南",
    "plugin-docs-update": "插件文档更新",
    "plugin-enabled-prefs-persistence": "插件启用偏好持久化",
    "plugin-entry-cache-bust": "插件入口缓存失效",
    "plugin-host-error-actions": "插件宿主错误处理",
    "plugin-host-icons": "插件宿主图标",
    "plugin-icon-system": "插件图标系统",
    "plugin-lifecycle-colocation": "插件生命周期共置",
    "plugin-pick-local-files": "插件选择本地文件",
    "plugin-registry-hostapi": "插件注册宿主API",
    "plugin-registry-i18n": "插件注册国际化",
    "plugin-shelf-toggle": "插件书架切换",
    "plugin-vue-bridge": "插件Vue桥接",
    "plugins-core-refactor": "插件核心重构",
    "registry-icon-upload": "注册图标上传",
    "remote-plugin-hmr": "远程插件HMR",
    "switch-dynamic-id-fix": "动态切换ID修复",

    # === react/ ===
    "use-chat-code-floating-toolbar": "聊天代码浮动工具条Hook",
    "use-stick-to-bottom-scroll": "吸底滚动Hook",
    "useSyncExternalStore": "外部同步存储Hook",

    # === setting/ ===
    "accent-color-settings": "强调色设置",
    "system-shortcuts-conflict-and-toast": "系统快捷键冲突与提示",
    "system-shortcuts-implementation-record": "系统快捷键实现记录",

    # === style/ ===
    "sonner-pointer-events-fix": "Sonner指针事件修复",
    "style-isolation-dev-exclude-host": "样式隔离开发排除宿主",
    "style-isolation-implementation": "样式隔离实现",
    "style-isolation-layered-refactor": "样式隔离分层重构",
    "style-isolation-modularization": "样式隔离模块化",
    "style-isolation-portal-overlay-timing": "样式隔离门户覆盖时序",
    "style-isolation-qiankun-harden": "样式隔离乾坤加固",
    "style-isolation-realm-portal": "样式隔离领域门户",
    "style-isolation-tech-overview": "样式隔离技术概述",

    # === tauri/ ===
    "about-window-lightweight": "关于窗口轻量化",
    "macos-drag-picker-crash": "macOS拖拽选择器崩溃",
    "tauri-browser": "Tauri浏览器",
    "tauri-fullscreen-sync": "Tauri全屏同步",
    "tauri-http-all-method-retry": "Tauri HTTP全方法重试",
    "tauri-macos-ats-http": "Tauri macOS ATS 通信",
    "tauri-system-menu-shortcuts": "Tauri系统菜单快捷键",
    "tauri-webview-context-menu-disable": "Tauri WebView右键菜单禁用",
    "tauri-window-zoom-unveil": "Tauri窗口缩放揭示",

    # === ui/ ===
    "monaco-loading-restore": "Monaco加载恢复",
    "rich-editor-feature": "富文本编辑器特性",
    "selection-drag-shell-scroll-guide": "选区拖拽壳层滚动指南",
    "standalone-preview-polish": "独立预览打磨",
    "tooltip-controlled-align": "提示受控对齐",
    "ui-tint-polish": "UI色调打磨",

    # === video/ ===
    "remote-demo-audio-player": "远程演示音频播放器",
    "video-player-chrome-cinema-theme": "视频播放器Chrome影院主题",
    "video-player-component-refactor": "视频播放器组件重构",
    "video-player-drag-scrub": "视频播放器拖拽进度",
    "video-player-feature-enhancement": "视频播放器功能增强",
    "video-player-plugin": "视频播放器插件",

    # === tools/ ===
    "markdown-fence-line-parser": "Markdown围栏行解析器",
    "usage-guide": "使用指南",

    # === i18n/ ===
    "i18n-zh-en-implementation-guide": "中英双语实现指南",
}


def main():
    count = 0

    # 收集所有 md 文件
    all_files = []
    for root, dirs, files in os.walk(BASE):
        for fname in files:
            if fname.endswith(".md"):
                all_files.append(os.path.join(root, fname))

    for filepath in all_files:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
        original = content

        # 对每个映射进行替换
        for old_base, new_base in RENAME_MAP.items():
            old_ref = old_base + ".md"
            new_ref = new_base + ".md"

            if old_ref not in content:
                continue

            # 替换：直接替换 .md 引用
            # 需要考虑路径前缀
            # 先检查 content 中出现的具体形式
            content = content.replace(old_ref, new_ref)

        if content != original:
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(content)
            count += 1
            rel = os.path.relpath(filepath, BASE)
            print(f"  Fixed: {rel}")

    print(f"\nFixed links in {count} files.")


if __name__ == "__main__":
    main()
