/** TTS 音频 L2 Redis 缓存（固定 TTL，无水位分档） */
export enum TtsCacheEnum {
	TTS_CACHE_L2_ENABLED = 'TTS_CACHE_L2_ENABLED',
	TTS_CACHE_TTL_SEC = 'TTS_CACHE_TTL_SEC',
	TTS_CACHE_MAX_VALUE_BYTES = 'TTS_CACHE_MAX_VALUE_BYTES',
	TTS_CACHE_REDIS_SOFT_MB = 'TTS_CACHE_REDIS_SOFT_MB',
	TTS_CACHE_GET_TIMEOUT_MS = 'TTS_CACHE_GET_TIMEOUT_MS',
	TTS_CACHE_SET_TIMEOUT_MS = 'TTS_CACHE_SET_TIMEOUT_MS',
	TTS_CACHE_CIRCUIT_FAILS = 'TTS_CACHE_CIRCUIT_FAILS',
	TTS_CACHE_CIRCUIT_OPEN_MS = 'TTS_CACHE_CIRCUIT_OPEN_MS',
}
