export enum ConfigEnum {
	DB_TYPE = 'DB_TYPE',
	DB_HOST = 'DB_HOST',
	DB_PORT = 'DB_PORT',
	DB_DB1_PORT = 'DB_DB1_PORT',
	DB_DB1_NAME = 'DB_DB1_NAME',
	DB_USERNAME = 'DB_USERNAME',
	DB_PASSWORD = 'DB_PASSWORD',
	DB_DATABASE = 'DB_DATABASE',
	DB_SYNC = 'DB_SYNC',
	DB_DB1_SYNC = 'DB_DB1_SYNC',
	SECRET = 'SECRET',
}

export enum LogEnum {
	LOG_LEVEL = 'LOG_LEVEL',
	LOG_ON = 'LOG_ON',
}

export enum RedisEnum {
	REDIS_URL = 'REDIS_URL',
	REDIS_PASSWORD = 'REDIS_PASSWORD',
	REDIS_USERNAME = 'REDIS_USERNAME',
}

export enum QiniuEnum {
	ACCESS_KEY = 'ACCESS_KEY',
	SECRET_KEY = 'SECRET_KEY',
	BUCKET_NAME = 'BUCKET_NAME',
	DOMAIN = 'DOMAIN',
}

export enum FileEnum {
	FILE_ROOT = 'FILE_ROOT',
}

export enum EmailEnum {
	EMAIL_TRANSPORT = 'EMAIL_TRANSPORT',
	EMAIL_FROM = 'EMAIL_FROM',
}
