pub mod dock;
pub mod event;
pub mod learning_notes_popout;
#[cfg(target_os = "macos")]
pub mod fullscreen_watch;
#[cfg(target_os = "macos")]
pub mod zoom;
pub mod menu;
pub mod shortcut;
pub mod tray;
