export const DEFAULT_INFO = [
	{
		label: '隐藏程序',
		key: 1,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: 'Command + W',
		placeholder: '按键盘输入快捷键',
		action: 'hide',
	},
	{
		label: '显示隐藏应用',
		key: 2,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: 'Meta + E',
		placeholder: '按键盘输入快捷键',
		action: 'hideOrShowApp',
	},
	{
		label: '刷新应用',
		key: 3,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: 'Command + Shift + W',
		placeholder: '按键盘输入快捷键',
		action: 'reload',
	},
	{
		label: '新建工作流',
		key: 4,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: 'Command + N',
		placeholder: '按键盘输入快捷键',
		action: 'new_workflow',
	},
	{
		label: '打开子窗口',
		key: 5,
		id: 'shortcut',
		shortcut: '',
		defaultShortcut: 'Ctrl + Shift + L',
		placeholder: '按键盘输入快捷键',
		action: 'open_subwindow',
	},
];
