import type { DailyVocabCard } from '../types';

/** 内置高频词（未登录或无收藏/复习队列时的默认词池） */
export const DAILY_STARTER_WORDS: DailyVocabCard[] = [
	{
		key: 'hello',
		word: 'hello',
		ipa: '/həˈloʊ/',
		pos: 'int.',
		segmentation: '',
		translationZh: '你好',
		example: 'Hello, how are you?',
		origin: 'starter',
	},
	{
		key: 'thank',
		word: 'thank',
		ipa: '/θæŋk/',
		pos: 'v.',
		segmentation: '',
		translationZh: '感谢',
		example: 'Thank you for your help.',
		origin: 'starter',
	},
	{
		key: 'water',
		word: 'water',
		ipa: '/ˈwɔːtər/',
		pos: 'n.',
		segmentation: '',
		translationZh: '水',
		example: 'I need a glass of water.',
		origin: 'starter',
	},
	{
		key: 'book',
		word: 'book',
		ipa: '/bʊk/',
		pos: 'n.',
		segmentation: '',
		translationZh: '书',
		example: 'This is a good book.',
		origin: 'starter',
	},
	{
		key: 'friend',
		word: 'friend',
		ipa: '/frend/',
		pos: 'n.',
		segmentation: '',
		translationZh: '朋友',
		example: 'She is my best friend.',
		origin: 'starter',
	},
	{
		key: 'happy',
		word: 'happy',
		ipa: '/ˈhæpi/',
		pos: 'adj.',
		segmentation: '',
		translationZh: '快乐的',
		example: 'I am happy today.',
		origin: 'starter',
	},
	{
		key: 'school',
		word: 'school',
		ipa: '/skuːl/',
		pos: 'n.',
		segmentation: '',
		translationZh: '学校',
		example: 'He goes to school every day.',
		origin: 'starter',
	},
	{
		key: 'time',
		word: 'time',
		ipa: '/taɪm/',
		pos: 'n.',
		segmentation: '',
		translationZh: '时间',
		example: 'What time is it?',
		origin: 'starter',
	},
	{
		key: 'good',
		word: 'good',
		ipa: '/ɡʊd/',
		pos: 'adj.',
		segmentation: '',
		translationZh: '好的',
		example: 'Have a good day!',
		origin: 'starter',
	},
	{
		key: 'love',
		word: 'love',
		ipa: '/lʌv/',
		pos: 'v.',
		segmentation: '',
		translationZh: '爱；喜欢',
		example: 'I love learning English.',
		origin: 'starter',
	},
	{
		key: 'home',
		word: 'home',
		ipa: '/hoʊm/',
		pos: 'n.',
		segmentation: '',
		translationZh: '家',
		example: 'I want to go home.',
		origin: 'starter',
	},
	{
		key: 'food',
		word: 'food',
		ipa: '/fuːd/',
		pos: 'n.',
		segmentation: '',
		translationZh: '食物',
		example: 'The food is delicious.',
		origin: 'starter',
	},
	{
		key: 'day',
		word: 'day',
		ipa: '/deɪ/',
		pos: 'n.',
		segmentation: '',
		translationZh: '天；白天',
		example: 'Have a nice day.',
		origin: 'starter',
	},
	{
		key: 'work',
		word: 'work',
		ipa: '/wɜːrk/',
		pos: 'v.',
		segmentation: '',
		translationZh: '工作',
		example: 'I work from nine to five.',
		origin: 'starter',
	},
	{
		key: 'people',
		word: 'people',
		ipa: '/ˈpiːpl/',
		pos: 'n.',
		segmentation: '',
		translationZh: '人们',
		example: 'Many people like music.',
		origin: 'starter',
	},
];
