export const options: any = {
	minimap: { enabled: false },
	fontSize: 14,
	lineHeight: 22,
	fontFamily: 'Fira Code, "SF Mono", "Monaco", "Menlo", "Consolas", monospace',
	fontLigatures: true,
	lineNumbers: 'on' as const,
	wordWrap: 'on' as const,
	colorDecorators: true,
	scrollBeyondLastLine: false,
	automaticLayout: true,
	padding: { top: 10, bottom: 10 },
	quickSuggestions: false,
	suggestOnTriggerCharacters: false,
	tabSize: 2,
	folding: true,
	foldingHighlight: true,
	foldingStrategy: 'indentation' as const,
	wordBasedSuggestions: 'allDocuments' as const,
	parameterHints: { enabled: false },
	snippetSuggestions: 'inline' as const,
	cursorBlinking: 'smooth' as const,
	cursorSmoothCaretAnimation: 'off' as const,
	renderLineHighlight: 'none' as const,
	hideCursorInOverviewRuler: true,
	overviewRulerBorder: false,
	contextmenu: false,
	scrollbar: {
		vertical: 'visible' as const,
		horizontal: 'visible' as const,
		verticalScrollbarSize: 8,
		horizontalScrollbarSize: 8,
	},
};
